"""add campaign rating and link to deal

Revision ID: 0c7b2eb09204
Revises: a76dff45e801
Create Date: 2026-02-13 17:43:06.738963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c7b2eb09204'
down_revision: Union[str, None] = 'a76dff45e801'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('rating_avg', sa.Float(), nullable=False, server_default='0'))
    op.add_column('campaigns', sa.Column('rating_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('deals', sa.Column('campaign_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_deals_campaign_id'), 'deals', ['campaign_id'], unique=False)
    op.add_column('reviews', sa.Column('target_campaign_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_reviews_target_campaign_id'), 'reviews', ['target_campaign_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reviews_target_campaign_id'), table_name='reviews')
    op.drop_column('reviews', 'target_campaign_id')
    op.drop_index(op.f('ix_deals_campaign_id'), table_name='deals')
    op.drop_column('deals', 'campaign_id')
    op.drop_column('campaigns', 'rating_count')
    op.drop_column('campaigns', 'rating_avg')
    # ### end Alembic commands ###
