"""add_role_based_ratings

Revision ID: a76dff45e801
Revises: 2ebdccc3ebf8
Create Date: 2026-02-13 00:50:45.525025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a76dff45e801'
down_revision: Union[str, None] = '2ebdccc3ebf8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('rating_advertiser_avg', sa.Float(), nullable=False, server_default='0.0'))
    op.add_column('users', sa.Column('rating_advertiser_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('users', sa.Column('rating_owner_avg', sa.Float(), nullable=False, server_default='0.0'))
    op.add_column('users', sa.Column('rating_owner_count', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'rating_owner_count')
    op.drop_column('users', 'rating_owner_avg')
    op.drop_column('users', 'rating_advertiser_count')
    op.drop_column('users', 'rating_advertiser_avg')
    # ### end Alembic commands ###
